# Configuration SonarCloud pour le Backend
sonar.organization=12052003
sonar.projectKey=Ozouka_Projet10OC-backend
sonar.projectName=bob-app-backend
sonar.projectVersion=1.0

# Sources du backend
sonar.sources=src/main/java
sonar.tests=src/test/java

# Inclusions des tests
sonar.test.inclusions=src/test/**/*.java

# Coverage report
sonar.java.jacoco.reportPaths=target/site/jacoco/jacoco.xml

# Exclusions
sonar.exclusions=target/**,src/main/resources/**

sonar.sourceEncoding=UTF-8 