# Configuration SonarCloud pour le Frontend
sonar.organization=12052003
sonar.projectKey=Ozouka_Projet10OC-frontend
sonar.projectName=bob-app-frontend
sonar.projectVersion=1.0

# Sources du frontend
sonar.sources=src/app
sonar.tests=src/app

# Inclusions des tests
sonar.test.inclusions=src/**/*.spec.ts,src/**/*.test.ts

# Coverage report
sonar.javascript.lcov.reportPaths=coverage/bobapp/lcov.info

# Exclusions
sonar.exclusions=node_modules/**,dist/**,src/environments/**,**/*.spec.ts

# Configuration TypeScript
sonar.typescript.tsconfigPath=tsconfig.json

sonar.sourceEncoding=UTF-8
