name: Backend CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./back
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          
      - name: Build with Maven
        run: mvn clean verify
          
      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: ${{ github.workspace }}/back/target/site/jacoco
          
      - name: Test Report
        uses: phoenix-actions/test-reporting@v8
        if: success() || failure()
        with:
          name: Tests Backend
          path: back/target/surefire-reports/*.xml
          reporter: java-junit

  sonarcloud-backend:
    needs: test-backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./back
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Build backend
        run: mvn clean verify

      - name: SonarCloud Scan Backend
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: -Dsonar.sources=back/src/main/java -Dsonar.tests=back/src/test/java -Dsonar.java.binaries=back/target/classes -Dsonar.java.test.binaries=back/target/test-classes -Dsonar.coverage.jacoco.xmlReportPaths=back/target/site/jacoco/jacoco.xml -Dsonar.exclusions=**/node_modules/**,**/dist/**,**/target/**,**/coverage/**,**/build/**
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  docker-backend:
    needs: [test-backend, sonarcloud-backend]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: back

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t bob-app-back .
          docker tag bob-app-back ${{ secrets.DOCKER_USERNAME }}/bob-app-back:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/bob-app-back:latest
