name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Message de succès
        run: echo "Yes super ça fonctionne !"

  docker-frontend:
    needs: test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t bob-app-front .
          docker tag bob-app-front ${{ vars.DOCKER_USERNAME }}/bob-app-front:latest
          docker push ${{ vars.DOCKER_USERNAME }}/bob-app-front:latest

  docker-backend:
    needs: test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: back

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t bob-app-back .
          docker tag bob-app-back ${{ vars.DOCKER_USERNAME }}/bob-app-back:latest
          docker push ${{ vars.DOCKER_USERNAME }}/bob-app-back:latest
