name: Tests et Couverture

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Build with Maven
        run: |
          cd back
          mvn clean verify
          
      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          path: back/target/site/jacoco/
          
      - name: Test Report
        uses: phoenix-actions/test-reporting@v8
        if: success() || failure()
        with:
          name: Tests Backend
          path: back/target/surefire-reports/*.xml
          reporter: java-junit

  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          cd front
          npm install
          
      - name: Run tests
        run: |
          cd front
          npm test -- --coverage
          
      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: frontend-coverage
          path: front/coverage/
          
      - name: Test Report
        uses: phoenix-actions/test-reporting@v8
        if: success() || failure()
        with:
          name: Tests Frontend
          path: front/junit.xml
          reporter: jest-junit 
